services:
  electroshop:
    build: .
    container_name: electroshop_container
    ports:
      - "8081:8080"
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/electroshop
      #SPRING_DATASOURCE_USERNAME: root
      #SPRING_DATASOURCE_PASSWORD: Shashank@1002
      SPRING_DATASOURCE_URL: jdbc:mysql://nozomi.proxy.rlwy.net:29274/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: wUyOzcLZsSrFZNCdInZFCGBZoEbquAOr
