version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Shashank@1002
      MYSQL_DATABASE: electroshop
    ports:
      - "3306:3306"

  electroshop:
    build: .
    container_name: electroshop_container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/electroshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Shashank@1002
