# DB Config
#spring.datasource.url=jdbc:mysql://localhost:3306/electroshop
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/electroshop
#spring.datasource.username=root
#spring.datasource.password=Shashank@1002

# DB Config
spring.datasource.url=jdbc:postgresql://electroshop_user:gmuZpweRf31QkUsN7IvGLGpzLpbHBGiq@dpg-d1vkpf3e5dus739siuu0-a/electroshop
spring.datasource.username=electroshop_user
spring.datasource.password=gmuZpweRf31QkUsN7IvGLGpzLpbHBGiq

# JPA Config 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
